import { defineFeature, type RegisteredFeature } from '../feature.js';

/** The built-in AI, and the rules that let it act on its own. */
export const AI_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'ki-chat',
    area: 'ki',
    since: '2026-08-05',
    ui: { path: '/chats' },
    settings: ['ai.enabled', 'ai.defaultModelSlug', 'ai.systemPrompt'],
    claims: { screens: ['/chats'] },
  }),
  defineFeature({
    id: 'chat-archiv',
    area: 'ki',
    since: '2026-09-08',
    ui: { path: '/chats' },
    tools: ['exo_chat_list', 'exo_chat_read', 'exo_chat_search'],
  }),
  defineFeature({
    id: 'ki-werkzeuge',
    area: 'ki',
    since: '2026-08-06',
    references: ['ADR-014', 'ADR-025', 'ADR-059', 'ADR-060'],
    ui: {},
    settings: ['ai.toolsEnabled', 'ai.mutatingToolsEnabled', 'ai.maxToolIterations'],
    tools: ['exo_toolbox'],
  }),
  defineFeature({
    id: 'seitenkontext',
    area: 'ki',
    since: '2026-08-06',
    references: ['ADR-015'],
    ui: {},
    settings: ['ai.pageContextEnabled', 'ai.pageContextMaxChars'],
  }),
  defineFeature({
    id: 'angeheftete-quellen',
    area: 'ki',
    since: '2026-09-19',
    references: ['#75', 'ADR-043'],
    ui: {},
    settings: ['ai.maxPinnedSources', 'ai.pinnedContextMaxChars'],
    tools: ['exo_chat_context'],
  }),
  defineFeature({
    id: 'bilder-verstehen',
    area: 'ki',
    since: '2026-08-06',
    ui: {},
    settings: ['ai.visionEnabled', 'ai.visionMaxImagesPerRun'],
  }),
  defineFeature({
    id: 'web-recherche',
    area: 'ki',
    since: '2026-09-18',
    references: ['#26', 'ADR-033'],
    ui: {},
    settings: [
      'ai.webResearchEnabled',
      'ai.webResearchMaxChars',
      'ai.webResearchMaxFetchesPerRun',
      'ai.webSearchMaxResults',
    ],
    tools: ['exo_web_search', 'exo_web_fetch'],
  }),
  defineFeature({
    id: 'fremdinhalte-sperre',
    area: 'ki',
    since: '2026-09-16',
    references: ['#56', 'ADR-030'],
    ui: {},
    settings: ['ai.untrustedContentPolicy'],
  }),
  defineFeature({
    id: 'kompaktierung',
    area: 'ki',
    since: '2026-08-06',
    references: ['ADR-032'],
    ui: {},
    settings: [
      'ai.compactionThresholdPercent',
      'ai.compactionKeepRecentMessages',
      'ai.compactionModelSlug',
    ],
  }),
  defineFeature({
    id: 'ki-regeln',
    area: 'ki',
    since: '2026-08-06',
    ui: {},
    tools: ['exo_rules_list', 'exo_rules_load', 'exo_page_set_ai_rule'],
  }),
  defineFeature({
    id: 'ki-laeufe',
    area: 'ki',
    since: '2026-08-06',
    references: ['ADR-059'],
    ui: {},
    settings: ['ai.maxRunMs', 'ai.timeoutMs', 'ai.budgetMicroUsdPerRun'],
    tools: ['exo_ai_run_get', 'exo_ai_run_cancel'],
  }),
  defineFeature({
    id: 'automationen',
    area: 'automationen',
    since: '2026-09-12',
    references: ['#50', 'ADR-024'],
    ui: {},
    settings: ['automations.enabled', 'automations.maxConsecutiveFailures'],
    tools: [
      'exo_automation_create',
      'exo_automation_update',
      'exo_automation_delete',
      'exo_automation_list',
      'exo_automation_runs',
      'exo_automation_trigger',
    ],
    claims: {
      screens: ['/arbeitsbereich/:x/automationen'],
      automationTriggers: [
        'DOCUMENT_CREATED',
        'DOCUMENT_UPDATED',
        'DOCUMENT_CONTENT_CHANGED',
        'DOCUMENT_MOVED',
        'DOCUMENT_ARCHIVED',
        'DOCUMENT_DELETED',
        'DATABASE_ROW_CHANGED',
      ],
    },
  }),
  defineFeature({
    id: 'automation-webhook',
    area: 'automationen',
    since: '2026-09-12',
    references: ['ADR-024'],
    ui: {},
    settings: ['automations.webhookAllowedHosts', 'automations.webhookTimeoutSeconds'],
    claims: { automationActions: ['WEBHOOK'] },
  }),
  defineFeature({
    id: 'automation-ki',
    area: 'automationen',
    since: '2026-09-12',
    references: ['ADR-024'],
    ui: {},
    settings: ['automations.runRetentionDays'],
    claims: { automationActions: ['AI_RUN'] },
  }),
  defineFeature({
    id: 'automation-mail',
    area: 'automationen',
    since: '2026-09-20',
    references: ['#104', 'ADR-054'],
    ui: {},
    claims: { automationActions: ['EMAIL_SELF'] },
  }),
  defineFeature({
    id: 'automation-fehlermeldung',
    area: 'automationen',
    since: '2026-09-24',
    references: ['#107', 'ADR-052'],
    ui: {
      path: '/einstellungen/benachrichtigungen',
    },
    settings: ['automations.maxConsecutiveFailures', 'notifications.digestTimeZone'],
  }),
  defineFeature({
    id: 'zeitplaene',
    area: 'automationen',
    since: '2026-09-18',
    references: ['#73', 'ADR-038'],
    ui: {},
    claims: { automationTriggers: ['SCHEDULE'] },
  }),
];
