import { defineFeature, type RegisteredFeature } from '../feature.js';

/** Working together, what happened before, and what the agents remember. */
export const COLLABORATION_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'echtzeit',
    area: 'zusammenarbeit',
    since: '2026-08-05',
    references: ['ADR-004', 'ADR-008'],
    ui: {},
  }),
  defineFeature({
    id: 'kommentare',
    area: 'zusammenarbeit',
    since: '2026-08-05',
    ui: {},
    shortcuts: ['Strg+. öffnet den Kontextbereich'],
    tools: [
      'exo_comment_create',
      'exo_comment_list',
      'exo_comment_update',
      'exo_comment_resolve',
      'exo_comment_delete',
    ],
  }),
  defineFeature({
    id: 'verlauf',
    area: 'zusammenarbeit',
    since: '2026-08-09',
    ui: {},
    settings: [
      'activity.editSessionSnapshotsEnabled',
      'activity.snapshotRetentionFullDays',
      'activity.snapshotRetentionDailyDays',
    ],
    tools: ['exo_page_activity', 'exo_page_snapshots', 'exo_page_restore_snapshot'],
  }),
  defineFeature({
    id: 'versionsvergleich',
    area: 'zusammenarbeit',
    since: '2026-09-19',
    ui: {},
    tools: ['exo_page_snapshot_diff', 'exo_page_restore_blocks'],
  }),
  defineFeature({
    id: 'agenten-journal',
    area: 'zusammenarbeit',
    since: '2026-09-13',
    references: ['ADR-022'],
    ui: {},
    settings: ['agents.journalRetentionDays'],
    tools: ['exo_agent_session_list', 'exo_agent_session_get'],
    claims: { screens: ['/admin/agenten'] },
  }),
  defineFeature({
    id: 'agenten-aenderungen-sehen',
    area: 'zusammenarbeit',
    since: '2026-09-25',
    references: ['#112', 'ADR-065'],
    ui: {},
  }),
  defineFeature({
    id: 'agenten-gedaechtnis',
    area: 'gedaechtnis',
    since: '2026-08-12',
    references: ['ADR-019', 'ADR-023'],
    ui: {},
    settings: ['memory.enabled', 'memory.captureModelSlug', 'memory.retentionDays'],
    tools: ['recall', 'remember'],
  }),
  defineFeature({
    id: 'gedaechtnis-checkpoint',
    area: 'gedaechtnis',
    since: '2026-09-20',
    references: ['ADR-019', 'ADR-046', '#92'],
    ui: {},
    settings: ['memory.enabled', 'memory.captureModelSlug', 'memory.retentionDays'],
  }),
  defineFeature({
    id: 'gedaechtnis-postfach',
    area: 'gedaechtnis',
    since: '2026-09-20',
    references: ['#51', 'ADR-047'],
    ui: {},
    settings: ['memory.mailboxEnabled', 'memory.messageExpiryDays', 'memory.recallMessageLimit'],
    tools: ['exo_agent_message_send', 'exo_agent_messages', 'exo_agent_message_read'],
  }),
  defineFeature({
    id: 'gedaechtnis-fakten',
    area: 'gedaechtnis',
    since: '2026-09-08',
    references: ['ADR-021'],
    ui: { path: '/gedaechtnis' },
    settings: [
      'memory.consolidationEnabled',
      'memory.factHalfLifeDays',
      'memory.factConfidenceFloor',
    ],
    tools: ['exo_memory_facts', 'exo_memory_fact_promote'],
    claims: { screens: ['/gedaechtnis'] },
  }),
  defineFeature({
    id: 'entitaeten',
    area: 'gedaechtnis',
    since: '2026-09-08',
    references: ['#47'],
    ui: { path: '/entitaeten' },
    settings: ['entities.enabled', 'entities.databaseId', 'entities.candidatesEnabled'],
    tools: [
      'exo_entity_create',
      'exo_entity_update',
      'exo_entity_list',
      'exo_entity_profile',
      'exo_entity_link_page',
      'exo_entity_unlink_page',
      'exo_entity_candidates',
      'exo_entity_candidate_confirm',
      'exo_entity_candidate_dismiss',
    ],
    claims: { screens: ['/entitaeten'] },
  }),
  defineFeature({
    id: 'auftraege',
    area: 'zusammenarbeit',
    since: '2026-09-26',
    references: ['#138', 'ADR-066'],
    ui: {},
    tools: [
      'exo_work_item_list',
      'exo_work_item_get',
      'exo_work_item_create',
      'exo_work_item_update',
      'exo_work_item_note',
      'exo_work_item_start_run',
      'exo_work_item_delete',
    ],
    claims: { screens: ['/arbeitsbereich/:x/auftraege', '/arbeitsbereich/:x/auftraege/:x'] },
  }),
  defineFeature({
    id: 'arbeitsstaende',
    area: 'zusammenarbeit',
    since: '2026-09-26',
    references: ['#142', 'ADR-069'],
    ui: {},
    tools: ['exo_work_item_checkpoint', 'exo_work_item_checkpoints'],
  }),
  defineFeature({
    id: 'wartet-auf-dich',
    area: 'zusammenarbeit',
    since: '2026-09-26',
    references: ['#139', 'ADR-067', '#140', 'ADR-068'],
    ui: {},
    tools: [
      'exo_attention_list',
      'exo_attention_get',
      'exo_attention_request',
      'exo_attention_resolve',
      'exo_attention_withdraw',
    ],
    claims: { screens: ['/wartet'] },
  }),
  defineFeature({
    id: 'aenderungsvorschlaege',
    area: 'zusammenarbeit',
    since: '2026-09-27',
    references: ['#141', 'ADR-070'],
    ui: {},
    settings: ['ai.writeMode'],
    tools: [
      'exo_changeset_propose',
      'exo_changeset_submit',
      'exo_changeset_remove_change',
      'exo_changeset_discard',
      'exo_changeset_get',
      'exo_changeset_list',
      'exo_changeset_apply',
      'exo_changeset_reject',
    ],
    claims: {
      screens: ['/arbeitsbereich/:x/vorschlaege', '/arbeitsbereich/:x/vorschlaege/:x'],
    },
  }),
];
