import { defineFeature, type RegisteredFeature } from '../feature.js';

/** Working together, what happened before, and what the agents remember. */
export const COLLABORATION_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'echtzeit',
    area: 'zusammenarbeit',
    since: '2026-08-05',
    references: ['ADR-004', 'ADR-008'],
    ui: {},
  }),
  defineFeature({
    id: 'kommentare',
    area: 'zusammenarbeit',
    since: '2026-08-05',
    ui: {},
    shortcuts: ['Strg+. öffnet den Kontextbereich'],
    tools: [
      'exo_comment_create',
      'exo_comment_list',
      'exo_comment_update',
      'exo_comment_resolve',
      'exo_comment_delete',
    ],
  }),
  defineFeature({
    id: 'verlauf',
    area: 'zusammenarbeit',
    since: '2026-08-09',
    ui: {},
    settings: [
      'activity.editSessionSnapshotsEnabled',
      'activity.snapshotRetentionFullDays',
      'activity.snapshotRetentionDailyDays',
    ],
    tools: ['exo_page_activity', 'exo_page_snapshots', 'exo_page_restore_snapshot'],
  }),
  defineFeature({
    id: 'versionsvergleich',
    area: 'zusammenarbeit',
    since: '2026-09-19',
    ui: {},
    tools: ['exo_page_snapshot_diff', 'exo_page_restore_blocks'],
  }),
  defineFeature({
    id: 'agenten-journal',
    area: 'zusammenarbeit',
    since: '2026-09-13',
    references: ['ADR-022'],
    ui: {},
    settings: ['agents.journalRetentionDays'],
    tools: ['exo_agent_session_list', 'exo_agent_session_get'],
    claims: { screens: ['/admin/agenten'] },
  }),
  defineFeature({
    id: 'agenten-gedaechtnis',
    area: 'gedaechtnis',
    since: '2026-08-12',
    references: ['ADR-019', 'ADR-023'],
    ui: {},
    settings: ['memory.enabled', 'memory.captureModelSlug', 'memory.retentionDays'],
    tools: ['recall', 'remember'],
  }),
  defineFeature({
    id: 'gedaechtnis-checkpoint',
    area: 'gedaechtnis',
    since: '2026-09-20',
    references: ['ADR-019', 'ADR-046', '#92'],
    ui: {},
    settings: ['memory.enabled', 'memory.captureModelSlug', 'memory.retentionDays'],
  }),
  defineFeature({
    id: 'gedaechtnis-postfach',
    area: 'gedaechtnis',
    since: '2026-09-20',
    references: ['#51', 'ADR-047'],
    ui: {},
    settings: ['memory.mailboxEnabled', 'memory.messageExpiryDays', 'memory.recallMessageLimit'],
    tools: ['exo_agent_message_send', 'exo_agent_messages', 'exo_agent_message_read'],
  }),
  defineFeature({
    id: 'gedaechtnis-fakten',
    area: 'gedaechtnis',
    since: '2026-09-08',
    references: ['ADR-021'],
    ui: { path: '/gedaechtnis' },
    settings: [
      'memory.consolidationEnabled',
      'memory.factHalfLifeDays',
      'memory.factConfidenceFloor',
    ],
    tools: ['exo_memory_facts', 'exo_memory_fact_promote'],
    claims: { screens: ['/gedaechtnis'] },
  }),
  defineFeature({
    id: 'entitaeten',
    area: 'gedaechtnis',
    since: '2026-09-08',
    references: ['#47'],
    ui: { path: '/entitaeten' },
    settings: ['entities.enabled', 'entities.databaseId', 'entities.candidatesEnabled'],
    tools: [
      'exo_entity_create',
      'exo_entity_update',
      'exo_entity_list',
      'exo_entity_profile',
      'exo_entity_link_page',
      'exo_entity_unlink_page',
      'exo_entity_candidates',
      'exo_entity_candidate_confirm',
      'exo_entity_candidate_dismiss',
    ],
    claims: { screens: ['/entitaeten'] },
  }),
];
