import { defineFeature, type RegisteredFeature } from '../feature.js';

/**
 * Pages, the structure they hang in, and finding them again.
 *
 * `since` is the day the capability went live on this deployment, which for
 * everything dated 2026-08-05 is the day the repository started: the editor and
 * the page tree were the first thing there was.
 */
export const PAGE_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'seiten-editor',
    area: 'seiten',
    since: '2026-08-05',
    references: ['ADR-004', 'ADR-005'],
    ui: {},
    tools: ['exo_page_create', 'exo_page_read', 'exo_page_write', 'exo_page_rename'],
    claims: { screens: ['/arbeitsbereich/:x/seite/:x'] },
  }),
  defineFeature({
    id: 'seiten-teilweise-schreiben',
    area: 'seiten',
    since: '2026-09-21',
    references: ['#111', 'ADR-055'],
    tools: ['exo_page_block_update', 'exo_page_patch', 'exo_page_section_write'],
  }),
  defineFeature({
    id: 'grosse-seiten-karte-und-auslagern',
    area: 'seiten',
    since: '2026-09-21',
    references: ['#118', 'ADR-056', 'ADR-045'],
    tools: ['exo_page_extract_section'],
  }),
  defineFeature({
    id: 'bloecke',
    area: 'seiten',
    since: '2026-08-05',
    ui: {},
    claims: { screens: ['/arbeitsbereich/:x/seite/:x'] },
  }),
  defineFeature({
    id: 'seiten-layout',
    area: 'seiten',
    since: '2026-08-05',
    ui: {},
    settings: ['ai.imageGenerationEnabled', 'ai.imageModelSlug'],
    tools: ['exo_page_set_cover', 'exo_page_set_layout', 'exo_page_generate_cover'],
  }),
  defineFeature({
    id: 'arbeitsbereiche',
    area: 'struktur',
    since: '2026-08-05',
    ui: { path: '/arbeitsbereich' },
    tools: ['exo_list_workspaces', 'exo_workspace_overview', 'exo_workspace_rename'],
    claims: { screens: ['/arbeitsbereich', '/arbeitsbereich/:x'] },
  }),
  defineFeature({
    id: 'seitenbaum',
    area: 'struktur',
    since: '2026-08-05',
    ui: {},
    shortcuts: ['Strg+B blendet die Navigation ein und aus, außerhalb von Textfeldern'],
    tools: ['exo_page_tree', 'exo_page_move'],
  }),
  defineFeature({
    id: 'ablage-vorschlag',
    area: 'struktur',
    since: '2026-09-16',
    ui: {},
    tools: ['exo_page_suggest_parent'],
  }),
  defineFeature({
    id: 'papierkorb',
    area: 'struktur',
    since: '2026-08-12',
    ui: {},
    tools: ['exo_page_archive', 'exo_page_restore', 'exo_page_trash', 'exo_page_delete'],
  }),
  defineFeature({
    id: 'vorlagen',
    area: 'struktur',
    since: '2026-09-18',
    references: ['#79', 'ADR-039'],
    ui: {},
    tools: [
      'exo_template_create',
      'exo_template_update',
      'exo_template_delete',
      'exo_template_list',
      'exo_template_use',
    ],
    claims: { screens: ['/arbeitsbereich/:x/vorlagen'] },
  }),
  defineFeature({
    id: 'transklusion',
    area: 'seiten',
    since: '2026-09-19',
    references: ['#78', 'ADR-045'],
    ui: {},
    tools: ['exo_page_block_read'],
  }),
  defineFeature({
    id: 'uebersichtsseiten',
    area: 'struktur',
    since: '2026-09-15',
    references: ['ADR-028'],
    ui: {},
    settings: ['overview.enabled', 'overview.modelSlug', 'overview.generateCovers'],
    tools: ['exo_page_set_overview', 'exo_page_overview_read', 'exo_page_overview_refresh'],
  }),
  defineFeature({
    id: 'suche',
    area: 'suche',
    since: '2026-08-05',
    references: ['ADR-020', 'ADR-034', 'ADR-058'],
    ui: {},
    shortcuts: ['Strg+K'],
    settings: [
      'search.semanticEnabled',
      'search.embeddingModelSlug',
      'search.semanticWeightPercent',
    ],
    tools: ['exo_search'],
  }),
  defineFeature({
    id: 'kontext-zusammenstellen',
    area: 'suche',
    since: '2026-09-24',
    references: ['ADR-061', 'ADR-034', 'ADR-044'],
    tools: ['exo_context_compile'],
  }),
  defineFeature({
    id: 'verweise',
    area: 'suche',
    since: '2026-08-09',
    ui: {},
    shortcuts: ['Strg+. öffnet den Kontextbereich'],
    tools: ['exo_page_backlinks', 'exo_page_related', 'exo_page_resolve_link'],
  }),
  defineFeature({
    id: 'gespeicherte-suchen',
    area: 'suche',
    since: '2026-09-19',
    references: ['#74', 'ADR-020', 'ADR-011'],
    ui: {
      path: '/arbeitsbereich',
    },
    shortcuts: ['Strg+K'],
    settings: ['search.semanticEnabled'],
    tools: [
      'exo_saved_query_list',
      'exo_saved_query_get',
      'exo_saved_query_preview',
      'exo_saved_query_run',
      'exo_saved_query_create',
      'exo_saved_query_update',
      'exo_saved_query_reorder',
      'exo_saved_query_delete',
    ],
    claims: { screens: ['/arbeitsbereich/:x/suche', '/arbeitsbereich/:x/suche/:x'] },
  }),
];
