import { defineFeature, type RegisteredFeature } from '../feature.js';

/** Getting in, letting agents in, and running the deployment. */
export const PLATFORM_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'funktionsuebersicht',
    area: 'hilfe',
    since: '2026-09-18',
    references: ['#80', 'ADR-040'],
    ui: { path: '/hilfe' },
    tools: ['exo_features'],
    claims: { screens: ['/hilfe'] },
  }),
  defineFeature({
    id: 'mcp-server',
    area: 'agenten',
    since: '2026-08-06',
    references: ['ADR-014', 'ADR-018', 'ADR-025'],
    ui: {},
    settings: ['mcp.enabled', 'mcp.maxSearchResults', 'mcp.writeConfirmationRequired'],
  }),
  defineFeature({
    id: 'mcp-ueber-http',
    area: 'agenten',
    since: '2026-08-11',
    references: ['ADR-018'],
    ui: { path: '/verbinden' },
    claims: { screens: ['/verbinden'] },
  }),
  defineFeature({
    id: 'mcp-abonnements',
    area: 'agenten',
    since: '2026-09-18',
    references: ['#48', 'ADR-035'],
    ui: {},
  }),
  defineFeature({
    id: 'deep-research-connector',
    area: 'agenten',
    since: '2026-08-11',
    ui: {},
    tools: ['search', 'fetch'],
  }),
  defineFeature({
    id: 'api-tokens',
    area: 'agenten',
    since: '2026-08-06',
    ui: { path: '/einstellungen/tokens' },
    claims: { screens: ['/einstellungen/tokens'] },
  }),
  defineFeature({
    id: 'token-seitenbereiche',
    area: 'agenten',
    since: '2026-09-19',
    references: ['#83', 'ADR-044'],
    ui: {},
  }),
  defineFeature({
    id: 'push-benachrichtigungen',
    area: 'agenten',
    since: '2026-09-20',
    references: ['#30', 'ADR-048'],
    ui: {},
    tools: [
      'exo_push_devices',
      'exo_push_device_update',
      'exo_push_device_remove',
      'exo_push_send',
    ],
  }),
  defineFeature({
    id: 'benachrichtigungen-einstellen',
    area: 'agenten',
    since: '2026-09-20',
    references: ['#105', '#106', '#107', 'ADR-052', 'ADR-053'],
    ui: {
      path: '/einstellungen/benachrichtigungen',
    },
    claims: { screens: ['/einstellungen/benachrichtigungen'] },
    tools: ['exo_notification_preferences', 'exo_notification_preference_set'],
  }),
  defineFeature({
    id: 'sprache-waehlen',
    area: 'hilfe',
    since: '2026-09-25',
    references: ['#98', 'ADR-062'],
    ui: { path: '/einstellungen/sprache' },
    claims: { screens: ['/einstellungen/sprache'] },
    tools: ['exo_me_preferences', 'exo_me_preferences_set'],
  }),
  defineFeature({
    id: 'verbindungen',
    area: 'agenten',
    since: '2026-08-12',
    references: ['ADR-029'],
    ui: { path: '/einstellungen/verbindungen' },
    claims: { screens: ['/einstellungen/verbindungen'] },
  }),
  defineFeature({
    id: 'anmeldung',
    area: 'verwaltung',
    since: '2026-08-05',
    ui: { path: '/anmelden' },
    claims: { screens: ['/anmelden', '/passwort-vergessen'] },
  }),
  defineFeature({
    id: 'einladungen',
    area: 'verwaltung',
    since: '2026-08-12',
    references: ['#3'],
    ui: {},
    tools: [
      'exo_invitation_create',
      'exo_invitation_list',
      'exo_invitation_resend',
      'exo_invitation_revoke',
    ],
    claims: { screens: ['/einladung/:x'] },
  }),
  defineFeature({
    id: 'nutzerverwaltung',
    area: 'verwaltung',
    since: '2026-08-12',
    ui: { path: '/admin/nutzer' },
    tools: ['exo_user_list', 'exo_user_set_disabled', 'exo_user_delete'],
    claims: { screens: ['/admin', '/admin/nutzer'] },
  }),
  defineFeature({
    id: 'einstellungen-geltungsbereiche',
    area: 'verwaltung',
    since: '2026-09-12',
    references: ['ADR-013', 'ADR-023'],
    ui: {
      path: '/admin/einstellungen',
    },
    claims: { screens: ['/admin/einstellungen', '/arbeitsbereich/:x/einstellungen'] },
  }),
  defineFeature({
    id: 'modell-registry',
    area: 'verwaltung',
    since: '2026-08-06',
    references: ['ADR-032'],
    ui: { path: '/admin/ki-modelle' },
    claims: { screens: ['/admin/ki-modelle'] },
  }),
  defineFeature({
    id: 'anbieter-routing',
    area: 'verwaltung',
    since: '2026-09-25',
    references: ['#135', 'ADR-063'],
    ui: {},
    settings: ['ai.providerRouting'],
  }),
  defineFeature({
    id: 'eigene-schluessel',
    area: 'verwaltung',
    since: '2026-09-12',
    ui: {},
  }),
  defineFeature({
    id: 'kosten',
    area: 'verwaltung',
    since: '2026-08-06',
    ui: { path: '/admin/nutzung' },
    settings: ['ai.runPayloadRetentionDays'],
    tools: ['exo_ai_usage'],
    claims: { screens: ['/admin/nutzung'] },
  }),
];
