import { defineFeature, type RegisteredFeature } from '../feature.js';

/** Turning what is written here into a file somebody else can read. */
export const PUBLISHING_FEATURES: readonly RegisteredFeature[] = [
  defineFeature({
    id: 'pdf-veroeffentlichen',
    area: 'veroeffentlichen',
    since: '2026-09-13',
    references: ['#44', 'ADR-026'],
    ui: {},
    settings: ['render.enabled', 'render.image', 'render.timeoutSeconds'],
    tools: [
      'exo_render_start',
      'exo_render_status',
      'exo_render_artifact',
      'exo_render_jobs',
      'exo_render_log',
      'exo_render_cancel',
      'exo_render_delete',
    ],
  }),
  defineFeature({
    id: 'render-vorlagen',
    area: 'veroeffentlichen',
    since: '2026-09-13',
    references: ['#44'],
    ui: {},
    tools: [
      'exo_render_template_create',
      'exo_render_template_read',
      'exo_render_template_update',
      'exo_render_template_delete',
      'exo_render_template_list',
    ],
  }),
  defineFeature({
    id: 'projekte',
    area: 'veroeffentlichen',
    since: '2026-09-13',
    references: ['#43', 'ADR-027'],
    ui: {},
    tools: [
      'exo_project_create',
      'exo_project_read',
      'exo_project_update',
      'exo_project_list',
      'exo_project_list_files',
      'exo_project_read_file',
      'exo_project_write_file',
      'exo_project_patch_file',
      'exo_project_move_file',
      'exo_project_delete_file',
      'exo_project_add_asset',
    ],
    claims: { screens: ['/arbeitsbereich/:x/projekt/:x'] },
  }),
  defineFeature({
    id: 'projekt-bauen',
    area: 'veroeffentlichen',
    since: '2026-09-13',
    references: ['#43'],
    ui: {},
    tools: [
      'exo_project_build',
      'exo_project_build_status',
      'exo_project_builds',
      'exo_project_build_log',
      'exo_project_build_artifacts',
      'exo_project_build_diagnostics',
      'exo_project_build_cancel',
      'exo_project_build_delete',
    ],
  }),
  defineFeature({
    id: 'synctex',
    area: 'veroeffentlichen',
    since: '2026-09-17',
    references: ['#53', '#70'],
    ui: {},
    tools: ['exo_project_build_position_of', 'exo_project_build_source_at'],
  }),
  defineFeature({
    id: 'projekt-archive',
    area: 'veroeffentlichen',
    since: '2026-09-17',
    references: ['#54'],
    ui: {},
    tools: ['exo_project_export', 'exo_project_import'],
  }),
  defineFeature({
    id: 'seiten-teilen',
    area: 'veroeffentlichen',
    since: '2026-09-20',
    references: ['#83', 'ADR-044'],
    ui: {},
    tools: [
      'exo_share_create',
      'exo_share_list',
      'exo_share_update',
      'exo_share_revoke',
      'exo_share_inherited',
    ],
    claims: { screens: ['/freigabe/:x'] },
  }),
  defineFeature({
    id: 'freigaben-uebersicht',
    area: 'veroeffentlichen',
    since: '2026-09-19',
    references: ['#83', 'ADR-044'],
    ui: {},
    tools: ['exo_shared_with_me', 'exo_share_workspace_list'],
    claims: { screens: ['/geteilt', '/geteilt/:x', '/arbeitsbereich/:x/freigaben'] },
  }),
  defineFeature({
    id: 'von-mir-geteilt',
    area: 'veroeffentlichen',
    since: '2026-09-24',
    references: ['#83', 'ADR-044'],
    ui: {
      path: '/geteilt',
    },
    tools: ['exo_share_mine'],
    claims: { screens: ['/geteilt'] },
  }),
];
