import { z } from 'zod';

import { LUCIDE_ICON_NAMES } from './lucide-icon-names';

/**
 * Identifiers are opaque strings generated by the server (cuid2 via Prisma).
 * Clients must never construct them.
 */
export const idSchema = z.string().min(8).max(64);
export type Id = z.infer<typeof idSchema>;

export const workspaceRoleSchema = z.enum(['OWNER', 'ADMIN', 'MEMBER', 'GUEST']);
export type WorkspaceRole = z.infer<typeof workspaceRoleSchema>;

/** Ordered from least to most privileged; used by the policy layer. */
export const WORKSPACE_ROLE_RANK: Record<WorkspaceRole, number> = {
  GUEST: 0,
  MEMBER: 1,
  ADMIN: 2,
  OWNER: 3,
};

/**
 * What a document row is.
 *
 * `PROJECT` (issue #43, ADR-027) is a file tree rather than prose: its Yjs
 * state holds paths and sources, and it is created through the project routes
 * rather than the generic one, which is why `createDocumentRequestSchema`
 * narrows the type it accepts.
 */
export const documentTypeSchema = z.enum(['PAGE', 'COLLECTION', 'PROJECT']);
export type DocumentType = z.infer<typeof documentTypeSchema>;

/** The types the generic create route accepts. See `documentTypeSchema`. */
export const creatableDocumentTypeSchema = z.enum(['PAGE', 'COLLECTION']);
export type CreatableDocumentType = z.infer<typeof creatableDocumentTypeSchema>;

export const collaborationAccessSchema = z.enum(['read', 'write']);
export type CollaborationAccess = z.infer<typeof collaborationAccessSchema>;

export const isoDateTimeSchema = z
  .union([z.string(), z.date()])
  .transform((value) => (value instanceof Date ? value.toISOString() : value));

export const paginationSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().min(1).optional(),
});
export type Pagination = z.infer<typeof paginationSchema>;

/**
 * Title constraints are shared by create/update/import so the same limit is
 * enforced everywhere.
 */
export const documentTitleSchema = z.string().trim().min(1).max(300);

/**
 * Prefix that marks a page icon as a *name* from the curated set below rather
 * than a literal character.
 *
 * One field carries both kinds of icon because they are one decision: a page has
 * exactly one symbol, and a second column would only ever hold the half of that
 * decision the first one did not. `📁` is stored verbatim, the drawn folder as
 * `lucide:folder`.
 */
export const DOCUMENT_ICON_NAME_PREFIX = 'lucide:';

/**
 * The drawable page icons the picker offers *before* anyone types.
 *
 * Every Lucide name validates (`LUCIDE_ICON_NAMES`), but 1,756 unsorted pictures
 * are not a choice, they are a wall. So this stays a curated, grouped shortlist:
 * it is what the picker opens on and what the MCP tool description names, and
 * the rest is reached by searching. Names are Lucide's own kebab-case ones, so
 * `apps/web` can map them to components without a translation table.
 */
export const DOCUMENT_ICON_NAMES = [
  // Filing
  'file-text',
  'files',
  'folder',
  'folder-open',
  'folder-tree',
  'book-open',
  'notebook-pen',
  'sticky-note',
  'bookmark',
  'archive',
  'inbox',
  'paperclip',
  // Marking
  'star',
  'heart',
  'flag',
  'pin',
  'sparkles',
  'flame',
  'zap',
  'target',
  'trophy',
  'bell',
  'circle-check',
  'triangle-alert',
  // Work
  'briefcase',
  'calendar',
  'clock',
  'timer',
  'list-checks',
  'clipboard-list',
  'chart-bar',
  'chart-line',
  'trending-up',
  'users',
  'mail',
  'message-circle',
  // Engineering
  'code',
  'terminal',
  'database',
  'server',
  'cpu',
  'git-branch',
  'bug',
  'wrench',
  'settings',
  'lock',
  'key',
  'shield',
  'network',
  'package',
  // Knowledge
  'brain',
  'lightbulb',
  'graduation-cap',
  'microscope',
  'palette',
  'pen-tool',
  'globe',
  'map',
  'compass',
  'newspaper',
  // Life
  'house',
  'map-pin',
  'plane',
  'car',
  'coffee',
  'utensils',
  'dumbbell',
  'leaf',
  'mountain',
  'sun',
  'moon',
  'gift',
] as const;
export type CuratedDocumentIconName = (typeof DOCUMENT_ICON_NAMES)[number];

/**
 * A Lucide icon name.
 *
 * Deliberately `string` and not a union of all 1,756 names: a union that wide
 * slows type checking down for a guarantee the compiler cannot give anyway,
 * because the name arrives from the database and from MCP clients at runtime.
 * `isLucideIconName` is the check that does hold.
 */
export type DocumentIconName = string;

/** Membership test behind `documentIconSchema`; a `Set` because the list is long. */
const LUCIDE_ICON_NAME_SET: ReadonlySet<string> = new Set(LUCIDE_ICON_NAMES);

export function isLucideIconName(value: string): boolean {
  return LUCIDE_ICON_NAME_SET.has(value);
}

/**
 * A page icon: either a literal character (an emoji) or `lucide:<name>`.
 *
 * `null` clears it and returns the page to the default icon for its type.
 *
 * The name is checked against every icon Lucide draws rather than against the
 * curated shortlist: the picker can search the whole set, so the shortlist is a
 * suggestion and refusing everything outside it would refuse what the picker
 * itself offers. An unknown name is still refused, because it would leave the
 * page with a symbol that renders as nothing.
 */
export const documentIconSchema = z
  .string()
  .trim()
  .min(1)
  .max(64)
  .refine(
    (value) =>
      !value.startsWith(DOCUMENT_ICON_NAME_PREFIX) ||
      isLucideIconName(value.slice(DOCUMENT_ICON_NAME_PREFIX.length)),
    { message: 'Unknown icon name' },
  )
  .nullable()
  .optional();

/**
 * Colour of a drawn page icon.
 *
 * The same nine names as the editor's content colours (`TEXT_COLOR_NAMES` in
 * `@exocortex/editor`), because the product has one palette and both render
 * through the `--content-*` tokens. They are repeated rather than imported:
 * contracts is a leaf package and depends on nothing.
 *
 * `null` means the icon inherits the surrounding text colour, which is what the
 * default icons have always done. An emoji brings its own colours, so the field
 * only takes effect on a `lucide:` icon.
 */
export const DOCUMENT_ICON_COLORS = [
  'gray',
  'brown',
  'orange',
  'yellow',
  'green',
  'blue',
  'purple',
  'pink',
  'red',
] as const;
export type DocumentIconColor = (typeof DOCUMENT_ICON_COLORS)[number];

export const documentIconColorSchema = z.enum(DOCUMENT_ICON_COLORS).nullable().optional();

/** Fractional index used for sibling ordering (see packages/database/order-key). */
export const orderKeySchema = z
  .string()
  .min(1)
  .max(120)
  .regex(/^[0-9A-Za-z]+$/, 'orderKey must contain only base62 characters');
