import { z } from 'zod';

/**
 * Identifiers are opaque strings generated by the server (cuid2 via Prisma).
 * Clients must never construct them.
 */
export const idSchema = z.string().min(8).max(64);
export type Id = z.infer<typeof idSchema>;

export const workspaceRoleSchema = z.enum(['OWNER', 'ADMIN', 'MEMBER', 'GUEST']);
export type WorkspaceRole = z.infer<typeof workspaceRoleSchema>;

/** Ordered from least to most privileged; used by the policy layer. */
export const WORKSPACE_ROLE_RANK: Record<WorkspaceRole, number> = {
  GUEST: 0,
  MEMBER: 1,
  ADMIN: 2,
  OWNER: 3,
};

export const documentTypeSchema = z.enum(['PAGE', 'COLLECTION']);
export type DocumentType = z.infer<typeof documentTypeSchema>;

export const collaborationAccessSchema = z.enum(['read', 'write']);
export type CollaborationAccess = z.infer<typeof collaborationAccessSchema>;

export const isoDateTimeSchema = z.union([z.string(), z.date()]).transform((value) =>
  value instanceof Date ? value.toISOString() : value,
);

export const paginationSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(20),
  cursor: z.string().min(1).optional(),
});
export type Pagination = z.infer<typeof paginationSchema>;

/**
 * Title constraints are shared by create/update/import so the same limit is
 * enforced everywhere.
 */
export const documentTitleSchema = z.string().trim().min(1).max(300);
export const documentIconSchema = z.string().trim().max(32).nullable().optional();

/** Fractional index used for sibling ordering (see packages/database/order-key). */
export const orderKeySchema = z
  .string()
  .min(1)
  .max(120)
  .regex(/^[0-9A-Za-z]+$/, 'orderKey must contain only base62 characters');
