// Generated by `node scripts/i18n/catalog.mjs` from src/messages. Do not edit:
// the i18n gate fails when this file no longer matches the message files.

import de_settings from './messages/de/settings.json';
import de_shell from './messages/de/shell.json';
import en_settings from './messages/en/settings.json';
import en_shell from './messages/en/shell.json';
import es_settings from './messages/es/settings.json';
import es_shell from './messages/es/shell.json';
import fr_settings from './messages/fr/settings.json';
import fr_shell from './messages/fr/shell.json';
import it_settings from './messages/it/settings.json';
import it_shell from './messages/it/shell.json';
import nl_settings from './messages/nl/settings.json';
import nl_shell from './messages/nl/shell.json';
import pl_settings from './messages/pl/settings.json';
import pl_shell from './messages/pl/shell.json';
import pt_BR_settings from './messages/pt-BR/settings.json';
import pt_BR_shell from './messages/pt-BR/shell.json';

export const NAMESPACES = ["settings","shell"] as const;

export const CATALOG = {
  'de': {
    "settings": de_settings,
    "shell": de_shell,
  },
  'en': {
    "settings": en_settings,
    "shell": en_shell,
  },
  'es': {
    "settings": es_settings,
    "shell": es_shell,
  },
  'fr': {
    "settings": fr_settings,
    "shell": fr_shell,
  },
  'it': {
    "settings": it_settings,
    "shell": it_shell,
  },
  'nl': {
    "settings": nl_settings,
    "shell": nl_shell,
  },
  'pl': {
    "settings": pl_settings,
    "shell": pl_shell,
  },
  'pt-BR': {
    "settings": pt_BR_settings,
    "shell": pt_BR_shell,
  },
} as const;
