// Generated by `node scripts/i18n/catalog.mjs` from src/messages. Do not edit:
// the i18n gate fails when this file no longer matches the message files.

import de_auth from './messages/de/auth.json';
import de_dialogs from './messages/de/dialogs.json';
import de_errors from './messages/de/errors.json';
import de_settings from './messages/de/settings.json';
import de_shell from './messages/de/shell.json';
import de_ui from './messages/de/ui.json';
import en_auth from './messages/en/auth.json';
import en_dialogs from './messages/en/dialogs.json';
import en_errors from './messages/en/errors.json';
import en_settings from './messages/en/settings.json';
import en_shell from './messages/en/shell.json';
import en_ui from './messages/en/ui.json';
import es_auth from './messages/es/auth.json';
import es_dialogs from './messages/es/dialogs.json';
import es_errors from './messages/es/errors.json';
import es_settings from './messages/es/settings.json';
import es_shell from './messages/es/shell.json';
import es_ui from './messages/es/ui.json';
import fr_auth from './messages/fr/auth.json';
import fr_dialogs from './messages/fr/dialogs.json';
import fr_errors from './messages/fr/errors.json';
import fr_settings from './messages/fr/settings.json';
import fr_shell from './messages/fr/shell.json';
import fr_ui from './messages/fr/ui.json';
import it_auth from './messages/it/auth.json';
import it_dialogs from './messages/it/dialogs.json';
import it_errors from './messages/it/errors.json';
import it_settings from './messages/it/settings.json';
import it_shell from './messages/it/shell.json';
import it_ui from './messages/it/ui.json';
import nl_auth from './messages/nl/auth.json';
import nl_dialogs from './messages/nl/dialogs.json';
import nl_errors from './messages/nl/errors.json';
import nl_settings from './messages/nl/settings.json';
import nl_shell from './messages/nl/shell.json';
import nl_ui from './messages/nl/ui.json';
import pl_auth from './messages/pl/auth.json';
import pl_dialogs from './messages/pl/dialogs.json';
import pl_errors from './messages/pl/errors.json';
import pl_settings from './messages/pl/settings.json';
import pl_shell from './messages/pl/shell.json';
import pl_ui from './messages/pl/ui.json';
import pt_BR_auth from './messages/pt-BR/auth.json';
import pt_BR_dialogs from './messages/pt-BR/dialogs.json';
import pt_BR_errors from './messages/pt-BR/errors.json';
import pt_BR_settings from './messages/pt-BR/settings.json';
import pt_BR_shell from './messages/pt-BR/shell.json';
import pt_BR_ui from './messages/pt-BR/ui.json';

export const NAMESPACES = ["auth","dialogs","errors","settings","shell","ui"] as const;

export const CATALOG = {
  'de': {
    "auth": de_auth,
    "dialogs": de_dialogs,
    "errors": de_errors,
    "settings": de_settings,
    "shell": de_shell,
    "ui": de_ui,
  },
  'en': {
    "auth": en_auth,
    "dialogs": en_dialogs,
    "errors": en_errors,
    "settings": en_settings,
    "shell": en_shell,
    "ui": en_ui,
  },
  'es': {
    "auth": es_auth,
    "dialogs": es_dialogs,
    "errors": es_errors,
    "settings": es_settings,
    "shell": es_shell,
    "ui": es_ui,
  },
  'fr': {
    "auth": fr_auth,
    "dialogs": fr_dialogs,
    "errors": fr_errors,
    "settings": fr_settings,
    "shell": fr_shell,
    "ui": fr_ui,
  },
  'it': {
    "auth": it_auth,
    "dialogs": it_dialogs,
    "errors": it_errors,
    "settings": it_settings,
    "shell": it_shell,
    "ui": it_ui,
  },
  'nl': {
    "auth": nl_auth,
    "dialogs": nl_dialogs,
    "errors": nl_errors,
    "settings": nl_settings,
    "shell": nl_shell,
    "ui": nl_ui,
  },
  'pl': {
    "auth": pl_auth,
    "dialogs": pl_dialogs,
    "errors": pl_errors,
    "settings": pl_settings,
    "shell": pl_shell,
    "ui": pl_ui,
  },
  'pt-BR': {
    "auth": pt_BR_auth,
    "dialogs": pt_BR_dialogs,
    "errors": pt_BR_errors,
    "settings": pt_BR_settings,
    "shell": pt_BR_shell,
    "ui": pt_BR_ui,
  },
} as const;
